### ISSUE TITLE
Kindred for extraction of numerical quantities related to entity of interest?

### ISSUE THREAD

**Issue by meaningfromdata** [jakelever/kindred#12]
Hi,
I am looking for an NLP tool in Python for extracting numerical quantities related to entities of interest in clinical text notes.  Is the kindred package suited to doing this?  For example, the text note might say something like:  "Expression of [entity] was found to be <5 %"  or " [Entity] Expression:  20%" or "[Entity] Expression 11-20 %."  I'd like to pull out the entity and its related quantity into a csv or some other structured format.  

Any other Python NLP packages you can suggest for this task?

Thanks

**Comment by jakelever** [comment]
Yes, I think Kindred should be able to do this, though I haven't tried it. Kindred does supervised learning so would need to be given a series of sentences with the desired relations annotated.

I'm not aware of any tools for extracting numerical quantities, though it must be a problem that others have looked into.

**Comment by meaningfromdata** [comment]
Thanks for reply.  My understanding is that Kindred can extract (or be trained to extract) relations between entities.  In my case I would have a relation between an entity and a number or sometimes a level of a categorical variable (e.g. "low" or "high" expression levels of the entity).  Would every numerical/categorical value need to be trained as an individual entity that relates to the other entity (a protein) of interest?  For example, expression could range from 0-100%.  Would those 101 percentage numbers all get trained as 101 entities?  Or could I just use the % sign itself as an entity but somehow still extract the number?

Thanks

**Comment by jakelever** [comment]
Sorry for the long delay. Had a big move but now settled in.

No, you wouldn't need examples of all possible values for a quantity. Kindred manages these entities by type. So maybe a sentence would contain a 'measurement' entity (e.g. voltage) and a quantity entity (e.g. 5). Then Kindred could learn to identify whether there is a relation between the 'measurement' entity and the 'quantity' entity.

I put together a bit of code to demonstrate this in [examples/quantities.py](https://github.com/jakelever/kindred/blob/master/examples/quantities.py). Please take a look at that as well as the new [tutorial](https://github.com/jakelever/kindred/tree/master/tutorial).

**Comment by wasimaftab** [comment]
Hi Jake,
Very interesting project. I have gone through the tutorial where you demonstrated annotation. I would like to use kindred to extract protein-protein interaction(PPI) from the literature. For testing purpose I would like to I create a corpus by downloading let's say 10 abstracts from Pubmed.
Since I am new to NLP, therefore, to quickly start working with kindred I have following questions
1. The names of entities i.e proteins should be in two files as I am looking for a relation between a pair of them? If yes then, do I need to have same list duplicated in two files as I don't know which protein do interact?
2. Can I use the annotate.py script to start annotating (isInteracting relation) them as you showed in tutorial?
3. Once I have them annotated how do I create a file listing all extracted protein-protein interactions.

Thanks for your time in advance
